---
title: "Cleaning data for occurrence and community databases" "Database #2 - -text_literature2021 " 

subtitle: 'EpIG volunteership'
format: html
editor: visual
date: today
author: "Kelly Zuluaga" 
editor_options: 
  chunk_output_type: console
---

#Libraries

```{r}
library(dplyr)
library(tidyverse)
library(stringr)
library(readr)
library(sf)
library(rWCVP)
library(CoordinateCleaner)
library(ggplot2) 

spp_link <- read.csv("data/Text/1_Raw/text__literature2021.csv")

head(spp_link)
View(spp_link)
str(spp_link)
glimpse(spp_link)


str(spp_link)
dplyr::glimpse(spp_link)
```



```{r}

#Dataset Structure

str(spp_link$taxonRank) #[1:10766] "SPECIES"
str(spp_link$lifeForm) #[1:10766] "NA"
str(spp_link$institutionCode) #[1:10766] "NA" 
str(spp_link$eventDate) #[1:10766] "NA" 
str(spp_link$ocurrenceID) #[1:10766] "NULL" 
str(spp_link$basisOfRecord) ##[1:10766] "MaterialCitation" 
str(spp_link$typeStatus) # #[1:10766] "NULL"  "Text"
str(spp_link$associatedReferences) #[1:10766]  - Needs review
str(spp_link$collectionCode) #[1:10766]
str(spp_link$recordedBy) ##[1:10766] Authors "NA"
str(spp_link$identifiedBy) ##[1:10766] "NA"
str(spp_link$datasetID) #[1:10766] "literature2021"
str(spp_link$matchCodeEpig) ##[1:10766]] Numbers ok
str(spp_link$matchedNameEpig) #[1:71897] Species ok
str(spp_link$typeStatus) ##[1:10766] "Text"
```


```{r}
#unique values in columns

sort(unique(spp_link$occurrenceID)) #ok

sort(unique(spp_link$basisOfRecord)) #ok

sort(unique(spp_link$typeStatus)) #ok

sort(unique(spp_link$associatedReferences)) #needs review

sort(unique(spp_link$institutionCode)) #ok

sort(unique(spp_link$taxonRank))#ok "FAMILY"  "GENUS"   "HYBRID"  "SPECIES"

sort(unique(spp_link$collectionCode)) #ok

sort(unique(spp_link$recordedBy)) #ok NA

sort(unique(spp_link$recordNumber)) #ok NA

sort(unique(spp_link$identifiedBy)) #needs curation

sort(unique(spp_link$lifeForm)) #ok NA

sort(unique(spp_link$datasetID)) #ok

sort(unique(spp_link$matchCodeEpig)) #ok  "0, 1, 2 or 3"

sort(unique(spp_link$matchedNameEpig)) #0, 1, 2 or 3

sort(unique(spp_link$decimalLatitude)) #ok

sort(unique(spp_link$decimalLongitude)) #ok

sort(unique(spp_link$eventDate)) #all dates are ok. Year column doesn't need

sort(unique(spp_link$changes)) #ok

#only curation in associatedReference

colnames(spp_link)
```

```{r}
#High detail inspection of data
#========================================================================
#ocurrenceID
#========================================================================

str(spp_link$occurrenceID)

summary(spp_link$occurrenceID)

sum(is.na(spp_link$occurrenceID))

sum(spp_link$occurrenceID == "")

length(unique(spp_link$occurrenceID))

nrow(spp_link)

anyDuplicated(spp_link$occurrenceID)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$occurrenceID)

#Not modifications

#========================================================================

#basisOfRecord

str(spp_link$basisOfRecord)

summary(spp_link$basisOfRecord)

sort(unique(spp_link$basisOfRecord))

table(spp_link$basisOfRecord,
      useNA = "ifany")

sum(is.na(spp_link$basisOfRecord))

sum(spp_link$basisOfRecord == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$basisOfRecord)

#complies with Darwin Core requirements

#========================================================================

#taxonRank


str(spp_link$taxonRank)

summary(spp_link$taxonRank)

sort(unique(spp_link$taxonRank))

table(spp_link$taxonRank,
      useNA = "ifany")

sum(is.na(spp_link$taxonRank))

sum(spp_link$taxonRank == "", na.rm = TRUE)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$taxonRank)


#taxonRank complies with Darwin Core requirements. At the word level, it's correct. However, Darwin Core spells it “subspecies” in lowercase.


#==============================================================================

#associatedReferences

str(spp_link$associatedReferences)

summary(spp_link$associatedReferences)

length(unique(spp_link$associatedReferences))

sum(is.na(spp_link$associatedReferences))

sum(spp_link$associatedReferences == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$associatedReferences)

grep("^\\s|\\s$", spp_link$associatedReferences)

grep("  +", spp_link$associatedReferences)

grep(",,", spp_link$associatedReferences)

grep("\\n|\\r", spp_link$associatedReferences)

grep("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$associatedReferences)

unique(spp_link$associatedReferences[
  grepl("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$associatedReferences)
])

#extract year of associatedReferences column

text_literature2021$referenceYear <- str_extract(
  text_literature2021$associatedReferences,
  "(19|20)\\d{2}"
)

text_literature2021$associatedReferenceAuthors <- str_trim(
  str_remove(
    text_literature2021$associatedReferences,
    "\\s*(19|20)\\d{2}[a-z]?$"
  )
)

#detect corrupted characters
text_literature2021$associatedReferences <- gsub(
  "CardelAºs", "Cárdenas",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "KrA¶mer", "Krömer",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "LA³pez-Villalobos", "López-Villalobos",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "MondragA³n", "Mondragón",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "NA¶ske", "Nöske",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "MagalhA£es", "Magalhaes",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "CasaA+/-as", "Casañas",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "JA!uregui", "Jáuregui",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "ProenA§a", "Proenca",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

text_literature2021$associatedReferences <- gsub(
  "GonA§alves", "Goncalves",
  text_literature2021$associatedReferences,
  fixed = TRUE
)

#change & by and 
spp_link$associatedReferences <- gsub(
  " y ",
  " & ",
  spp_link$associatedReferences
)


# =============================================================================
# referenceYear/"evendate"
# =============================================================================


#created referenceYear


# Extraer el año
text_literature2021$referenceYear <- sub(
  ".*((19|20)[0-9]{2}).*",
  "\\1",
  text_literature2021$associatedReferences
)

# Si no encontró un año, dejar NA

text_literature2021$referenceYear[
  !grepl("(19|20)[0-9]{2}", text_literature2021$associatedReferences)
] <- NA

# Eliminar el año de associatedReferences
text_literature2021$associatedReferences <- trimws(
  gsub("\\s*(19|20)[0-9]{2}[a-z]?$", "",
       text_literature2021$associatedReferences)
)

spp_link$associatedReferences <- gsub(
  "ArA\\(C\\)valo & Betancur",
  "Arevalo & Betancur",
  spp_link$associatedReferences
)

grep("ArA", spp_link$associatedReferences, value = TRUE)

grep("daSilva", spp_link$associatedReferences, value = TRUE)

#review

View(data.frame(
  associatedReferences = sort(unique(spp_link$associatedReferences))
))

```

```{r}
# =============================================================================
# identifiedBy 
# =============================================================================

# Inspection

str(spp_link$identifiedBy)

summary(spp_link$identifiedBy)

length(unique(spp_link$identifiedBy))

sum(is.na(spp_link$identifiedBy))

sum(spp_link$identifiedBy == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$identifiedBy)

grep("^\\s|\\s$", spp_link$identifiedBy)

grep("  +", spp_link$identifiedBy)

grep(",,", spp_link$identifiedBy)

grep("\\n|\\r", spp_link$identifiedBy)

grep("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$identifiedBy)

unique(
  spp_link$identifiedBy[
    grepl("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$identifiedBy)
  ]
)


# Remove accent marks


spp_link$identifiedBy <- delete_accents(spp_link$identifiedBy)


# Standardize compound surnames

spp_link$identifiedBy <- hyphenate_surname(spp_link$identifiedBy)


# Review unique values

unique_identifiedBy <- data.frame(
  identifiedBy = sort(unique(spp_link$identifiedBy))
)

View(unique_identifiedBy)

spp_link$recordedBy   <- delete_accents(spp_link$recordedBy)
spp_link$recordedBy   <- hyphenate_surname(spp_link$recordedBy)

spp_link$identifiedBy <- delete_accents(spp_link$identifiedBy)
spp_link$identifiedBy <- hyphenate_surname(spp_link$identifiedBy)

#add space between letters
spp_link$identifiedBy <- gsub("\\s*&\\s*", " & ", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\s*-\\s*", " - ", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\(RYS\\)", "(R Y S)", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\(CyC\\)", "(C y C)", spp_link$identifiedBy)
sort(unique(grep("Grupo de", spp_link$identifiedBy, value = TRUE)))
unique(spp_link$identifiedBy[grep("Grupo de", spp_link$identifiedBy)])

View(data.frame(
  identifiedBy = sort(unique(spp_link$identifiedBy))
))



#delete commons
spp_link$identifiedBy[grepl(",", spp_link$identifieddBy)] <- ""

# Keep a backup of the curated column

identifiedBy_curated <- spp_link$identifiedBy

#delete "()"

spp_link$identifiedBy <- gsub("[()]", "", spp_link$identifiedBy)

idx <- grepl("^\\s*,\\s*$", spp_link$identifiedBy)

spp_link$recordedBy[idx] <- ""

idx <- trimws(spp_link$identifiedBy) == ","

spp_link$identifiedBy[idx] <- NA_character_

dput(unique(spp_link$identifiedBy[grepl(",", spp_link$identifiedBy, fixed = TRUE)]))

unique(spp_link$identifiedBy)
#all data are curated for now
```



```{r}
#Export curated CVS

readr::write_csv(
  spp_link,
  "data/text/2.Processed/text__literature2021.csv",
  na = ""
)
```

