---
title: "Cleaning data for occurrence and community databases" "Database #2 - -text_zuluaga_a_2021 " 

subtitle: 'EpIG volunteership'
format: html
editor: visual
date: today
author: "Kelly Zuluaga" 
editor_options: 
  chunk_output_type: console
---

#Libraries

```{r}
library(dplyr)
library(tidyverse)
library(stringr)
library(readr)
library(sf)
library(rWCVP)
library(CoordinateCleaner)
library(ggplot2) 

spp_link <- read.csv(
  "C:/Users/kelly/Downloads/EpiG V2/EpIG_volunteership/data/Text/1_Raw/text__zuluaga_a_2021.csv"
)

head(spp_link)
View(spp_link)
str(spp_link)
glimpse(spp_link)


str(spp_link)
dplyr::glimpse(spp_link)
```



```{r}

#Dataset Structure

str(spp_link$taxonRank) #[1:4486] "SPECIES"
str(spp_link$lifeForm) #[1:4486] "NA"
str(spp_link$institutionCode) #[1:4486] "MO" "CAS" "US" "A" "A" "B" "MO" "MO" "P" "P" "" "AMAZ" .
str(spp_link$eventDate) #[1:4486] ok
str(spp_link$ocurrenceID) #[1:4486] "NULL" ok
str(spp_link$basisOfRecord) #[1:4486] "PreservedSpecimen" ok
str(spp_link$typeStatus) # [1:4486] "NA"  ok
str(spp_link$associatedReferences) # [1:4486] "NA" ok
str(spp_link$collectionCode) #[1:4486] "NA" ok
str(spp_link$recordedBy) ##[1:4486] Authors -- needs curation
str(spp_link$identifiedBy) ##[1:4486] "NA" ok
str(spp_link$datasetID) #[1:4486] "zuluaga_a_2021" ok
str(spp_link$matchCodeEpig) ##[1:4486]] Numbers ok
str(spp_link$matchedNameEpig) #[1:4486] Species ok
str(spp_link$typeStatus) #[1:4486] "NA" ok
```




```{r}
#unique values in columns

sort(unique(spp_link$occurrenceID)) #ok

sort(unique(spp_link$basisOfRecord)) #ok

sort(unique(spp_link$typeStatus)) #ok

sort(unique(spp_link$associatedReferences)) #ok

sort(unique(spp_link$institutionCode)) #ok

sort(unique(spp_link$taxonRank))#ok "SPECIES"

sort(unique(spp_link$collectionCode)) #ok

sort(unique(spp_link$recordedBy)) #needs curation

sort(unique(spp_link$recordNumber)) #ok 

sort(unique(spp_link$identifiedBy)) #needs curation

sort(unique(spp_link$lifeForm)) #ok NA

sort(unique(spp_link$datasetID)) #ok NA

sort(unique(spp_link$matchCodeEpig)) #ok  "0, 1, 2 or 3"

sort(unique(spp_link$matchedNameEpig)) #0, 1, 2 or 3

sort(unique(spp_link$decimalLatitude)) #ok

sort(unique(spp_link$decimalLongitude)) #ok

sort(unique(spp_link$eventDate)) #all dates are ok. Year column doesn't need

sort(unique(spp_link$changes)) #ok

#only curation in identifiedBy column

colnames(spp_link)
```

```{r}
#High detail inspection of data
# =============================================================================
# identifiedBy 
# =============================================================================

# Inspection

str(spp_link$identifiedBy)

summary(spp_link$identifiedBy)

length(unique(spp_link$identifiedBy))

sum(is.na(spp_link$identifiedBy))

sum(spp_link$identifiedBy == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$identifiedBy)

grep("^\\s|\\s$", spp_link$identifiedBy)

grep("  +", spp_link$identifiedBy)

grep(",,", spp_link$identifiedBy)

grep("\\n|\\r", spp_link$identifiedBy)

grep("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$identifiedBy)

unique(
  spp_link$identifiedBy[
    grepl("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$identifiedBy)
  ]
)


# Remove accent marks


spp_link$identifiedBy <- delete_accents(spp_link$identifiedBy)


# Standardize compound surnames

spp_link$identifiedBy <- hyphenate_surname(spp_link$identifiedBy)


# Review unique values

unique_identifiedBy <- data.frame(
  identifiedBy = sort(unique(spp_link$identifiedBy))
)

View(unique_identifiedBy)

spp_link$recordedBy   <- delete_accents(spp_link$recordedBy)
spp_link$recordedBy   <- hyphenate_surname(spp_link$recordedBy)

spp_link$identifiedBy <- delete_accents(spp_link$identifiedBy)
spp_link$identifiedBy <- hyphenate_surname(spp_link$identifiedBy)

#add space between letters
spp_link$identifiedBy <- gsub("\\s*&\\s*", " & ", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\s*-\\s*", " - ", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\(RYS\\)", "(R Y S)", spp_link$identifiedBy)
spp_link$identifiedBy <- gsub("\\(CyC\\)", "(C y C)", spp_link$identifiedBy)
sort(unique(grep("Grupo de", spp_link$identifiedBy, value = TRUE)))
unique(spp_link$identifiedBy[grep("Grupo de", spp_link$identifiedBy)])

View(data.frame(
  identifiedBy = sort(unique(spp_link$identifiedBy))
))



#delete commons
spp_link$identifiedBy[grepl(",", spp_link$identifieddBy)] <- ""

# Keep a backup of the curated column

identifiedBy_curated <- spp_link$identifiedBy

#delete "()"

spp_link$identifiedBy <- gsub("[()]", "", spp_link$identifiedBy)

idx <- grepl("^\\s*,\\s*$", spp_link$identifiedBy)

spp_link$recordedBy[idx] <- ""

idx <- trimws(spp_link$identifiedBy) == ","

spp_link$identifiedBy[idx] <- NA_character_

dput(unique(spp_link$identifiedBy[grepl(",", spp_link$identifiedBy, fixed = TRUE)]))

unique(spp_link$identifiedBy)
#all data are curated for now
```



```{r}

#Preview dataset
View(spp_link) 

#Export curated CVS

readr::write_csv(
  spp_link,
  "data/text/2.Processed/text__literature2021.csv",
  na = ""
)
```
---
