---
title: "Cleaning data for occurrence and community databases" "Database #2 - text__zuluaga_a_2021.csv " 

subtitle: 'EpIG volunteership'
format: html
editor: visual
date: today
author: "Kelly Zuluaga" 
editor_options: 
  chunk_output_type: console
---

#Libraries

```{r}
library(dplyr)
library(tidyverse)
library(stringr)
library(readr)
library(sf)
library(rWCVP)
library(CoordinateCleaner)
library(ggplot2) 

spp_link <- read.csv("data/Text/1_Raw/text__zuluaga_a_2021.csv")

head(spp_link)
View(spp_link)
str(spp_link)
glimpse(spp_link)


str(spp_link)
dplyr::glimpse(spp_link)
```

```{r}

#Dataset Structure

str(spp_link$taxonRank) #[1:4486] "SPECIES"
str(spp_link$lifeForm) #[1:4486] "SPECIES"
str(spp_link$institutionCode) #[1:4486] "MO; CAS; US; A; P; AMAZ" 
str(spp_link$eventDate) #[1:4886] "NA" 
str(spp_link$ocurrenceID) #[1:4886] "NULL" 
str(spp_link$basisOfRecord) #[1:4486] "PreservedSpecimen" 
str(spp_link$typeStatus) # [1:4486] "NA"
str(spp_link$associatedReferences) #[1:4486] NA
str(spp_link$collectionCode) #[1:4486] NA
str(spp_link$recordedBy) #[1:4486] Authors Needs review
str(spp_link$identifiedBy) #[1:4486] "NA"
str(spp_link$datasetID) #[1:4486] "zuluaga_a_2021"
str(spp_link$matchCodeEpig) #[1:4486] Numbers ok
str(spp_link$matchedNameEpig) #[1:4486] Species ok
str(spp_link$typeStatus) ##[1:4486] "NA"
```

```{r}
#unique values in columns

sort(unique(spp_link$occurrenceID)) #ok

sort(unique(spp_link$basisOfRecord)) #ok

sort(unique(spp_link$typeStatus)) #ok

sort(unique(spp_link$associatedReferences)) #needs review

sort(unique(spp_link$institutionCode)) #ok

sort(unique(spp_link$taxonRank))#ok "FAMILY"  "GENUS"   "HYBRID"  "SPECIES"

sort(unique(spp_link$collectionCode)) #ok

sort(unique(spp_link$recordedBy)) #Needs curation

sort(unique(spp_link$recordNumber)) #ok 

sort(unique(spp_link$identifiedBy)) #ok

sort(unique(spp_link$lifeForm)) #ok 

sort(unique(spp_link$datasetID)) #ok

sort(unique(spp_link$matchCodeEpig)) #ok  

sort(unique(spp_link$matchedNameEpig)) #0, 1, 2 or 3

sort(unique(spp_link$decimalLatitude)) #ok

sort(unique(spp_link$decimalLongitude)) #ok

sort(unique(spp_link$eventDate)) #all dates are ok. Year column doesn't need

sort(unique(spp_link$changes)) #ok

#only curation in recordedBy

colnames(spp_link)
```

```{r}
#High detail inspection of data
#========================================================================
#ocurrenceID
#========================================================================

str(spp_link$occurrenceID)

summary(spp_link$occurrenceID)

sum(is.na(spp_link$occurrenceID))

sum(spp_link$occurrenceID == "")

length(unique(spp_link$occurrenceID))

nrow(spp_link)

anyDuplicated(spp_link$occurrenceID)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$occurrenceID)

#Not modifications

#========================================================================

#basisOfRecord

str(spp_link$basisOfRecord)

summary(spp_link$basisOfRecord)

sort(unique(spp_link$basisOfRecord))

table(spp_link$basisOfRecord,
      useNA = "ifany")

sum(is.na(spp_link$basisOfRecord))

sum(spp_link$basisOfRecord == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$basisOfRecord)

#complies with Darwin Core requirements

#========================================================================

#taxonRank


str(spp_link$taxonRank)

summary(spp_link$taxonRank)

sort(unique(spp_link$taxonRank))

table(spp_link$taxonRank,
      useNA = "ifany")

sum(is.na(spp_link$taxonRank))

sum(spp_link$taxonRank == "", na.rm = TRUE)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$taxonRank)


#taxonRank complies with Darwin Core requirements. At the word level, it's correct. However, Darwin Core spells it “subspecies” in lowercase.


#==============================================================================

#associatedReferences

str(spp_link$associatedReferences)

summary(spp_link$associatedReferences)

length(unique(spp_link$associatedReferences))

sum(is.na(spp_link$associatedReferences))

sum(spp_link$associatedReferences == "")


```

```{r}
# =============================================================================
# identifiedBy 
# =============================================================================

# Inspection

str(spp_link$identifiedBy)

summary(spp_link$identifiedBy)

length(unique(spp_link$identifiedBy))

sum(is.na(spp_link$identifiedBy))

sum(spp_link$identifiedBy == "")


```


```{r}
# =============================================================================
# recordedBy 
# =============================================================================

# Inspection

str(spp_link$recordedBy)

summary(spp_link$recordedBy)

length(unique(spp_link$recordedBy))

sum(is.na(spp_link$recordedBy))

sum(spp_link$recordedBy == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$recordedBy)

grep("^\\s|\\s$", spp_link$recordedBy)

grep("  +", spp_link$recordedBy)

grep(",,", spp_link$recordedBy)

grep("\\n|\\r", spp_link$recordedBy)

grep("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$recordedBy)

unique(spp_link$recordedBy[spp_link$recordedBy])

sort(unique(spp_link$recordedBy))

sort(table(spp_link$recordedBy), decreasing = TRUE)

library(stringi)

spp_link$recordedBy <- stri_trans_general(
  spp_link$recordedBy,
  "Latin-ASCII"
)

spp_link$recordedBy <- gsub(
  ", \\*$",
  "",
  spp_link$recordedBy
)


spp_link$recordedBy <- gsub(
  "StAhl, Bertil",
  "Stahl, Bertil",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "GrE†ger, Andreas",
  "Grager, Andreas",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "LA¯jtnant, Bernt",
  "Lojtnant, Bernt",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "Pittier, Henri FranAois",
  "Pittier, Henri Francois",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "MerxmA¸ller, Hermann",
  "Merxmueller, Hermann",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "JA¯rgensen, Peter MA¯ller",
  "Jorgensen, Peter Muller",
  spp_link$recordedBy,
  fixed = TRUE
)

sum(spp_link$recordedBy == ",", na.rm = TRUE)
spp_link$recordedBy[spp_link$recordedBy == ","] <- NA_character_
unique(spp_link$recordedBy[spp_link$recordedBy == ","])

# Normalizar apellidos escritos completamente en mayúsculas
spp_link$recordedBy <- gsub(
  "^BITTNER(,|$)", "Bittner\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^BILLIET(,|$)", "Billiet\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^BONIFAZ(,|$)", "Bonifaz\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^CHOCCE(,|$)", "Chocce\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^GRANT(,|$)", "Grant\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^RESTREPO(,|$)", "Restrepo\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MACEDO(,|$)", "Macedo\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MACIEL(,|$)", "Maciel\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MILLIKEN(,|$)", "Milliken\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MORICAND(,|$)", "Moricand\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^PELEGRIN-R(,|$)", "Pelegrin-R\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^SARASTEGUL(,|$)", "Sarastegul\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^SALIK(,|$)", "Salik\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^TEXIXEIRA(,|$)", "Texixeira\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^TIPAZ(,|$)", "Tipaz\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^WEBER(,|$)", "Weber\\1",
  spp_link$recordedBy
)


spp_link$recordedBy <- gsub(
  "^DANIEL(,|$)", "Daniel\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^FERRERIA(,|$)", "Ferreira\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^LUCKE(,|$)", "Lucke\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MCDOWELL(,|$)", "MCDowell\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^FERREIRA(,|$)", "Ferreira\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^JIMPIKIT(,|$)", "Jimpikit\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MUNICH(,|$)", "Munich\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^MAIA(,|$)", "Maia\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^RUDAS(,|$)", "Rudas\\1",
  spp_link$recordedBy
)


spp_link$recordedBy <- gsub(
  "^CERON(,|$)", "Ceron\\1",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "FE†rther, H.",
  "Forther, H.",
  spp_link$recordedBy,
  fixed = TRUE
)
grep("Forther|FE†rther", spp_link$recordedBy, value = TRUE)



spp_link$recordedBy <- gsub(
  "GonAalves, Eduardo G.",
  "Goncalves, Eduardo G.",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "Glaziou, Auguste FranAois Marie",
  "Glaziou, Auguste Francois Marie",
  spp_link$recordedBy,
  fixed = TRUE
)

grep(
  "Goncalves|Glaziou",
  spp_link$recordedBy,
  value = TRUE
)

spp_link$recordedBy <- gsub(
  "LA:;CRUCES, \\*",
  "Las-Cruces",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "^KOSTER$",
  "Koster",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "KrE†mer, Thorsten",
  "Kromer, Thorsten",
  spp_link$recordedBy,
  fixed = TRUE
)

spp_link$recordedBy <- gsub(
  "^RUDAS$",
  "Rudas",
  spp_link$recordedBy
)

spp_link$recordedBy <- gsub(
  "^SAGASTEGUL$",
  "Sagastegul",
  spp_link$recordedBy
  

)


spp_link$recordedBy <- gsub("^SPEARS$", "Spears", spp_link$recordedBy)
spp_link$recordedBy <- gsub("^STEWARD$", "Steward", spp_link$recordedBy)
spp_link$recordedBy <- gsub("^STORR$", "Storr", spp_link$recordedBy)
spp_link$recordedBy <- gsub("^SUAREZ$", "Suarez", spp_link$recordedBy)
spp_link$recordedBy <- gsub("^TEMPONI$", "Temponi", spp_link$recordedBy)
spp_link$recordedBy <- gsub("^XAVIER$", "Xavier", spp_link$recordedBy)

spp_link$recordedBy[spp_link$recordedBy == "LA:;CRUCES"] <- "Las-Cruces"

View(data.frame(
  recordedBy = sort(unique(spp_link$recordedBy))
))
```



```{r}

#Preview dataset
View(spp_link) 

#Export curated CVS

readr::write_csv(
  spp_link,
  "data/text/2.Processed/text__literature2021.csv",
  na = ""
)

```
