---
title: "Cleaning data for occurrence and community databases" "Database #2 - text__zuluaga_a_2021.csv " 

subtitle: 'EpIG volunteership'
format: html
editor: visual
date: today
author: "Kelly Zuluaga" 
editor_options: 
  chunk_output_type: console
---

#Libraries

```{r}
library(dplyr)
library(tidyverse)
library(stringr)
library(readr)
library(sf)
#library(rWCVP)
library(CoordinateCleaner)
library(ggplot2) 


spp_link <- read.csv("../../data/Text/1_Raw/text__kroemer_t_2024.csv")

head(spp_link)
View(spp_link)
str(spp_link)
glimpse(spp_link)


str(spp_link)
dplyr::glimpse(spp_link)
```

```{r}

#Dataset Structure

str(spp_link$taxonRank) #[1:270] "SPECIES"
str(spp_link$lifeForm) #[1:270] "E, NV..."
str(spp_link$institutionCode) #[1:270] "E" 
str(spp_link$eventDate) #[1:270] ok 
str(spp_link$ocurrenceID) #[1:270] "ok" 
str(spp_link$basisOfRecord) #[1:270] "PreservedSpecimen" ok
str(spp_link$typeStatus) # [1:270] "NA" ok
str(spp_link$associatedReferences) #[1:270] NA ok
str(spp_link$collectionCode) #[1:270] NA ok
str(spp_link$recordedBy) #[1:270] NA ok
str(spp_link$identifiedBy) #[1:270] "NA"
str(spp_link$datasetID) #[1:270] "kroemer_t_2024"
str(spp_link$matchCodeEpig) #[1:270] Numbers ok
str(spp_link$matchedNameEpig) #[1:270] Species ok
str(spp_link$typeStatus) ##[1:270] "NA"
```

```{r}
#unique values in columns

sort(unique(spp_link$occurrenceID)) #ok

sort(unique(spp_link$basisOfRecord)) #ok

sort(unique(spp_link$typeStatus)) #ok

sort(unique(spp_link$associatedReferences)) #ok

sort(unique(spp_link$institutionCode)) #ok

sort(unique(spp_link$taxonRank))#ok "FAMILY"  "GENUS"   "HYBRID"  "SPECIES"

sort(unique(spp_link$collectionCode)) #ok

sort(unique(spp_link$recordedBy)) #Needs curation

sort(unique(spp_link$recordNumber)) #ok 

sort(unique(spp_link$identifiedBy)) #ok

sort(unique(spp_link$lifeForm)) #ok 

sort(unique(spp_link$datasetID)) #ok

sort(unique(spp_link$matchCodeEpig)) #ok  

sort(unique(spp_link$matchedNameEpig)) #0, 1, 2 or 3

sort(unique(spp_link$decimalLatitude)) #ok

sort(unique(spp_link$decimalLongitude)) #ok

sort(unique(spp_link$eventDate)) #all dates are ok. Year column doesn't need

sort(unique(spp_link$changes)) #ok

#only curation in recordedBy

colnames(spp_link)
```

```{r}
#High detail inspection of data
#========================================================================
#ocurrenceID
#========================================================================

str(spp_link$occurrenceID)

summary(spp_link$occurrenceID)

sum(is.na(spp_link$occurrenceID))

sum(spp_link$occurrenceID == "")

length(unique(spp_link$occurrenceID))

nrow(spp_link)

anyDuplicated(spp_link$occurrenceID)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$occurrenceID)

#Not modifications

#========================================================================

#basisOfRecord

str(spp_link$basisOfRecord)

summary(spp_link$basisOfRecord)

sort(unique(spp_link$basisOfRecord))

table(spp_link$basisOfRecord,
      useNA = "ifany")

sum(is.na(spp_link$basisOfRecord))

sum(spp_link$basisOfRecord == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$basisOfRecord)

#complies with Darwin Core requirements

#========================================================================

#taxonRank


str(spp_link$taxonRank)

summary(spp_link$taxonRank)

sort(unique(spp_link$taxonRank))

table(spp_link$taxonRank,
      useNA = "ifany")

sum(is.na(spp_link$taxonRank))

sum(spp_link$taxonRank == "", na.rm = TRUE)

grep("Ã|Â|ƒ|\\n|\\r", spp_link$taxonRank)



#==============================================================================

#associatedReferences

str(spp_link$associatedReferences)

summary(spp_link$associatedReferences)

length(unique(spp_link$associatedReferences))

sum(is.na(spp_link$associatedReferences))

sum(spp_link$associatedReferences == "")


```

```{r}
# =============================================================================
# identifiedBy 
# =============================================================================

# Inspection

str(spp_link$identifiedBy)

summary(spp_link$identifiedBy)

length(unique(spp_link$identifiedBy))

sum(is.na(spp_link$identifiedBy))

sum(spp_link$identifiedBy == "")


```


```{r}
# =============================================================================
# recordedBy 
# =============================================================================

# Inspection

str(spp_link$recordedBy)

summary(spp_link$recordedBy)

length(unique(spp_link$recordedBy))

sum(is.na(spp_link$recordedBy))

sum(spp_link$recordedBy == "")

grep("Ã|Â|ƒ|\\n|\\r", spp_link$recordedBy)

grep("^\\s|\\s$", spp_link$recordedBy)

grep("  +", spp_link$recordedBy)

grep(",,", spp_link$recordedBy)

grep("\\n|\\r", spp_link$recordedBy)

grep("[ÁÉÍÓÚáéíóúÑñÜü]", spp_link$recordedBy)

unique(spp_link$recordedBy[spp_link$recordedBy])

sort(unique(spp_link$recordedBy))

sort(table(spp_link$recordedBy), decreasing = TRUE)

View(data.frame(
  recordedBy = sort(unique(spp_link$recordedBy))
))
```



```{r}

#All dataset are correct. It doesn't need more curations

#Preview dataset
View(spp_link) 

#Export curated CVS

readr::write_csv(
  spp_link,
  "data/text/2.Processed/text__kroemer_t_2024.csv",
  na = ""
)

```
